"""init professional platform schema

Revision ID: 7987b9d25a7f
Revises: 
Create Date: 2026-05-06 09:10:48.612782
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7987b9d25a7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plan_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('role_name', sa.String(length=128), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_role_code'), 'roles', ['role_code'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_index(op.f('ix_subjects_tenant_id'), 'subjects', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('scope_type', sa.String(length=64), nullable=False),
    sa.Column('scope_config_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result_summary_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_subject_id'), 'analysis_jobs', ['subject_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_tenant_id'), 'analysis_jobs', ['tenant_id'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('scope_config_json', sa.JSON(), nullable=True),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_subject_id'), 'analysis_reports', ['subject_id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_tenant_id'), 'analysis_reports', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('ocr_status', sa.String(length=32), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_sha256'), 'assets', ['sha256'], unique=True)
    op.create_index(op.f('ix_assets_subject_id'), 'assets', ['subject_id'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('auth_token_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_token_sessions_refresh_token_hash'), 'auth_token_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_auth_token_sessions_tenant_id'), 'auth_token_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auth_token_sessions_user_id'), 'auth_token_sessions', ['user_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_subject_id'), 'chapters', ['subject_id'], unique=False)
    op.create_index(op.f('ix_chapters_tenant_id'), 'chapters', ['tenant_id'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_exam', sa.String(length=128), nullable=True),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('preferred_subjects_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_profiles_tenant_id'), 'learner_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_learner_profiles_user_id'), 'learner_profiles', ['user_id'], unique=False)
    op.create_table('mock_exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('exam_mode', sa.String(length=64), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_exams_subject_id'), 'mock_exams', ['subject_id'], unique=False)
    op.create_index(op.f('ix_mock_exams_tenant_id'), 'mock_exams', ['tenant_id'], unique=False)
    op.create_table('question_bank_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('canonical_stem', sa.Text(), nullable=False),
    sa.Column('canonical_options_json', sa.JSON(), nullable=True),
    sa.Column('canonical_answer', sa.Text(), nullable=True),
    sa.Column('canonical_analysis', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=64), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_items_subject_id'), 'question_bank_items', ['subject_id'], unique=False)
    op.create_index(op.f('ix_question_bank_items_tenant_id'), 'question_bank_items', ['tenant_id'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('review_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_target_id'), 'review_tasks', ['target_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_tenant_id'), 'review_tasks', ['tenant_id'], unique=False)
    op.create_table('subject_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_categories_subject_id'), 'subject_categories', ['subject_id'], unique=False)
    op.create_index(op.f('ix_subject_categories_tenant_id'), 'subject_categories', ['tenant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('exam_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('paper_name', sa.String(length=255), nullable=False),
    sa.Column('paper_code', sa.String(length=64), nullable=True),
    sa.Column('exam_year', sa.Integer(), nullable=True),
    sa.Column('exam_month', sa.Integer(), nullable=True),
    sa.Column('exam_region', sa.String(length=64), nullable=True),
    sa.Column('exam_type', sa.String(length=64), nullable=True),
    sa.Column('paper_type', sa.String(length=64), nullable=True),
    sa.Column('source_channel', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_question_count', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('parsed_version', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_papers_asset_id'), 'exam_papers', ['asset_id'], unique=False)
    op.create_index(op.f('ix_exam_papers_subject_id'), 'exam_papers', ['subject_id'], unique=False)
    op.create_index(op.f('ix_exam_papers_tenant_id'), 'exam_papers', ['tenant_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('bank_question_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_question_id'], ['question_bank_items.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_bank_question_id'), 'favorites', ['bank_question_id'], unique=False)
    op.create_index(op.f('ix_favorites_learner_id'), 'favorites', ['learner_id'], unique=False)
    op.create_index(op.f('ix_favorites_tenant_id'), 'favorites', ['tenant_id'], unique=False)
    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['subject_categories.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_points_subject_id'), 'knowledge_points', ['subject_id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_tenant_id'), 'knowledge_points', ['tenant_id'], unique=False)
    op.create_table('mock_exam_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mock_exam_id', sa.Integer(), nullable=False),
    sa.Column('bank_question_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_question_id'], ['question_bank_items.id'], ),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_exam_questions_bank_question_id'), 'mock_exam_questions', ['bank_question_id'], unique=False)
    op.create_index(op.f('ix_mock_exam_questions_mock_exam_id'), 'mock_exam_questions', ['mock_exam_id'], unique=False)
    op.create_index(op.f('ix_mock_exam_questions_tenant_id'), 'mock_exam_questions', ['tenant_id'], unique=False)
    op.create_table('practice_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_report_id', sa.Integer(), nullable=True),
    sa.Column('difficulty_policy', sa.String(length=64), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_report_id'], ['analysis_reports.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sets_subject_id'), 'practice_sets', ['subject_id'], unique=False)
    op.create_index(op.f('ix_practice_sets_tenant_id'), 'practice_sets', ['tenant_id'], unique=False)
    op.create_table('knowledge_point_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_point_aliases_knowledge_point_id'), 'knowledge_point_aliases', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_knowledge_point_aliases_tenant_id'), 'knowledge_point_aliases', ['tenant_id'], unique=False)
    op.create_table('knowledge_point_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_kp_id', sa.Integer(), nullable=False),
    sa.Column('to_kp_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_kp_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['to_kp_id'], ['knowledge_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_point_relations_from_kp_id'), 'knowledge_point_relations', ['from_kp_id'], unique=False)
    op.create_index(op.f('ix_knowledge_point_relations_tenant_id'), 'knowledge_point_relations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_knowledge_point_relations_to_kp_id'), 'knowledge_point_relations', ['to_kp_id'], unique=False)
    op.create_table('mastery_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('answered_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mastery_snapshots_knowledge_point_id'), 'mastery_snapshots', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_mastery_snapshots_learner_id'), 'mastery_snapshots', ['learner_id'], unique=False)
    op.create_index(op.f('ix_mastery_snapshots_subject_id'), 'mastery_snapshots', ['subject_id'], unique=False)
    op.create_index(op.f('ix_mastery_snapshots_tenant_id'), 'mastery_snapshots', ['tenant_id'], unique=False)
    op.create_table('paper_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=128), nullable=False),
    sa.Column('question_type', sa.String(length=64), nullable=False),
    sa.Column('start_no', sa.Integer(), nullable=True),
    sa.Column('end_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_sections_paper_id'), 'paper_sections', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_sections_tenant_id'), 'paper_sections', ['tenant_id'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('practice_set_id', sa.Integer(), nullable=True),
    sa.Column('mock_exam_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('accuracy_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], ),
    sa.ForeignKeyConstraint(['practice_set_id'], ['practice_sets.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_learner_id'), 'practice_sessions', ['learner_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_subject_id'), 'practice_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_tenant_id'), 'practice_sessions', ['tenant_id'], unique=False)
    op.create_table('practice_set_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practice_set_id', sa.Integer(), nullable=False),
    sa.Column('bank_question_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_question_id'], ['question_bank_items.id'], ),
    sa.ForeignKeyConstraint(['practice_set_id'], ['practice_sets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_set_questions_bank_question_id'), 'practice_set_questions', ['bank_question_id'], unique=False)
    op.create_index(op.f('ix_practice_set_questions_practice_set_id'), 'practice_set_questions', ['practice_set_id'], unique=False)
    op.create_index(op.f('ix_practice_set_questions_tenant_id'), 'practice_set_questions', ['tenant_id'], unique=False)
    op.create_table('exam_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('question_no', sa.String(length=32), nullable=False),
    sa.Column('question_uid', sa.String(length=64), nullable=False),
    sa.Column('question_type', sa.String(length=64), nullable=False),
    sa.Column('stem_text', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('source_page_from', sa.Integer(), nullable=True),
    sa.Column('source_page_to', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_group_id', sa.String(length=64), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['paper_sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_questions_paper_id'), 'exam_questions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_exam_questions_question_uid'), 'exam_questions', ['question_uid'], unique=True)
    op.create_index(op.f('ix_exam_questions_section_id'), 'exam_questions', ['section_id'], unique=False)
    op.create_index(op.f('ix_exam_questions_subject_id'), 'exam_questions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_exam_questions_tenant_id'), 'exam_questions', ['tenant_id'], unique=False)
    op.create_table('practice_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('bank_question_id', sa.Integer(), nullable=False),
    sa.Column('learner_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('spent_seconds', sa.Integer(), nullable=True),
    sa.Column('knowledge_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_question_id'], ['question_bank_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_answers_bank_question_id'), 'practice_answers', ['bank_question_id'], unique=False)
    op.create_index(op.f('ix_practice_answers_session_id'), 'practice_answers', ['session_id'], unique=False)
    op.create_index(op.f('ix_practice_answers_tenant_id'), 'practice_answers', ['tenant_id'], unique=False)
    op.create_table('wrong_book_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('bank_question_id', sa.Integer(), nullable=False),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_question_id'], ['question_bank_items.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ),
    sa.ForeignKeyConstraint(['source_session_id'], ['practice_sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wrong_book_items_bank_question_id'), 'wrong_book_items', ['bank_question_id'], unique=False)
    op.create_index(op.f('ix_wrong_book_items_learner_id'), 'wrong_book_items', ['learner_id'], unique=False)
    op.create_index(op.f('ix_wrong_book_items_tenant_id'), 'wrong_book_items', ['tenant_id'], unique=False)
    op.create_table('question_knowledge_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_layer', sa.String(length=32), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('tag_source', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_knowledge_links_knowledge_point_id'), 'question_knowledge_links', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_question_knowledge_links_question_id'), 'question_knowledge_links', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_knowledge_links_tenant_id'), 'question_knowledge_links', ['tenant_id'], unique=False)
    op.create_table('question_source_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_question_id', sa.Integer(), nullable=False),
    sa.Column('exam_question_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_region', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_question_id'], ['question_bank_items.id'], ),
    sa.ForeignKeyConstraint(['exam_question_id'], ['exam_questions.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_source_links_bank_question_id'), 'question_source_links', ['bank_question_id'], unique=False)
    op.create_index(op.f('ix_question_source_links_exam_question_id'), 'question_source_links', ['exam_question_id'], unique=False)
    op.create_index(op.f('ix_question_source_links_paper_id'), 'question_source_links', ['paper_id'], unique=False)
    op.create_index(op.f('ix_question_source_links_tenant_id'), 'question_source_links', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_source_links_tenant_id'), table_name='question_source_links')
    op.drop_index(op.f('ix_question_source_links_paper_id'), table_name='question_source_links')
    op.drop_index(op.f('ix_question_source_links_exam_question_id'), table_name='question_source_links')
    op.drop_index(op.f('ix_question_source_links_bank_question_id'), table_name='question_source_links')
    op.drop_table('question_source_links')
    op.drop_index(op.f('ix_question_knowledge_links_tenant_id'), table_name='question_knowledge_links')
    op.drop_index(op.f('ix_question_knowledge_links_question_id'), table_name='question_knowledge_links')
    op.drop_index(op.f('ix_question_knowledge_links_knowledge_point_id'), table_name='question_knowledge_links')
    op.drop_table('question_knowledge_links')
    op.drop_index(op.f('ix_wrong_book_items_tenant_id'), table_name='wrong_book_items')
    op.drop_index(op.f('ix_wrong_book_items_learner_id'), table_name='wrong_book_items')
    op.drop_index(op.f('ix_wrong_book_items_bank_question_id'), table_name='wrong_book_items')
    op.drop_table('wrong_book_items')
    op.drop_index(op.f('ix_practice_answers_tenant_id'), table_name='practice_answers')
    op.drop_index(op.f('ix_practice_answers_session_id'), table_name='practice_answers')
    op.drop_index(op.f('ix_practice_answers_bank_question_id'), table_name='practice_answers')
    op.drop_table('practice_answers')
    op.drop_index(op.f('ix_exam_questions_tenant_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_subject_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_section_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_question_uid'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_paper_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index(op.f('ix_practice_set_questions_tenant_id'), table_name='practice_set_questions')
    op.drop_index(op.f('ix_practice_set_questions_practice_set_id'), table_name='practice_set_questions')
    op.drop_index(op.f('ix_practice_set_questions_bank_question_id'), table_name='practice_set_questions')
    op.drop_table('practice_set_questions')
    op.drop_index(op.f('ix_practice_sessions_tenant_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_subject_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_learner_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_paper_sections_tenant_id'), table_name='paper_sections')
    op.drop_index(op.f('ix_paper_sections_paper_id'), table_name='paper_sections')
    op.drop_table('paper_sections')
    op.drop_index(op.f('ix_mastery_snapshots_tenant_id'), table_name='mastery_snapshots')
    op.drop_index(op.f('ix_mastery_snapshots_subject_id'), table_name='mastery_snapshots')
    op.drop_index(op.f('ix_mastery_snapshots_learner_id'), table_name='mastery_snapshots')
    op.drop_index(op.f('ix_mastery_snapshots_knowledge_point_id'), table_name='mastery_snapshots')
    op.drop_table('mastery_snapshots')
    op.drop_index(op.f('ix_knowledge_point_relations_to_kp_id'), table_name='knowledge_point_relations')
    op.drop_index(op.f('ix_knowledge_point_relations_tenant_id'), table_name='knowledge_point_relations')
    op.drop_index(op.f('ix_knowledge_point_relations_from_kp_id'), table_name='knowledge_point_relations')
    op.drop_table('knowledge_point_relations')
    op.drop_index(op.f('ix_knowledge_point_aliases_tenant_id'), table_name='knowledge_point_aliases')
    op.drop_index(op.f('ix_knowledge_point_aliases_knowledge_point_id'), table_name='knowledge_point_aliases')
    op.drop_table('knowledge_point_aliases')
    op.drop_index(op.f('ix_practice_sets_tenant_id'), table_name='practice_sets')
    op.drop_index(op.f('ix_practice_sets_subject_id'), table_name='practice_sets')
    op.drop_table('practice_sets')
    op.drop_index(op.f('ix_mock_exam_questions_tenant_id'), table_name='mock_exam_questions')
    op.drop_index(op.f('ix_mock_exam_questions_mock_exam_id'), table_name='mock_exam_questions')
    op.drop_index(op.f('ix_mock_exam_questions_bank_question_id'), table_name='mock_exam_questions')
    op.drop_table('mock_exam_questions')
    op.drop_index(op.f('ix_knowledge_points_tenant_id'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_subject_id'), table_name='knowledge_points')
    op.drop_table('knowledge_points')
    op.drop_index(op.f('ix_favorites_tenant_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_learner_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_bank_question_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_exam_papers_tenant_id'), table_name='exam_papers')
    op.drop_index(op.f('ix_exam_papers_subject_id'), table_name='exam_papers')
    op.drop_index(op.f('ix_exam_papers_asset_id'), table_name='exam_papers')
    op.drop_table('exam_papers')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_tenant_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_subject_categories_tenant_id'), table_name='subject_categories')
    op.drop_index(op.f('ix_subject_categories_subject_id'), table_name='subject_categories')
    op.drop_table('subject_categories')
    op.drop_index(op.f('ix_review_tasks_tenant_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_target_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_question_bank_items_tenant_id'), table_name='question_bank_items')
    op.drop_index(op.f('ix_question_bank_items_subject_id'), table_name='question_bank_items')
    op.drop_table('question_bank_items')
    op.drop_index(op.f('ix_mock_exams_tenant_id'), table_name='mock_exams')
    op.drop_index(op.f('ix_mock_exams_subject_id'), table_name='mock_exams')
    op.drop_table('mock_exams')
    op.drop_index(op.f('ix_learner_profiles_user_id'), table_name='learner_profiles')
    op.drop_index(op.f('ix_learner_profiles_tenant_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_index(op.f('ix_chapters_tenant_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_subject_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_auth_token_sessions_user_id'), table_name='auth_token_sessions')
    op.drop_index(op.f('ix_auth_token_sessions_tenant_id'), table_name='auth_token_sessions')
    op.drop_index(op.f('ix_auth_token_sessions_refresh_token_hash'), table_name='auth_token_sessions')
    op.drop_table('auth_token_sessions')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_subject_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_sha256'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_analysis_reports_tenant_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_subject_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_analysis_jobs_tenant_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_subject_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_tenant_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
